format = "projecttypes/v1"
id = "c465ed9d-546f-44ba-b519-eb3c036fda01"
name = "OSWP Exam Report v1.1"
language = "en-US"
finding_field_order = [
    "title",
    "description",
    "proof",
    "screenshots",
    "steps",
    "cvss",
]
report_template = """
<div id="footer" data-sysreptor-generated="page-footer">
    <div id="footer-left"><em>CONFIDENTIAL</em></div>
    <div id="footer-center">{{ report.title }}</div>
</div>

<div v-if="report.watermark" id="watermark-osid">{{ report.osid }}</div>


<section id="page-cover" data-sysreptor-generated="page-cover">
    <div id="page-cover-background" />
    <div id="page-cover-title">
        <h1>Offensive Security</h1>
        <h2>{{ report.title }}</h2>
    </div>

    <div id="page-cover-student">
        <p id="page-cover-osid">
            <strong>OSID: {{ report.osid }}</strong><br>
            {{ report.mail }}<br>
        </p>
        <p id="page-cover-meta">
            {{ formatDate(report.report_date, 'long') }}<br>
            v{{ report.report_version }}
        </p>
    </div>
</section>
<pagebreak />


<table-of-contents id="toc" v-slot="tocItems">
    <h1>Table of Contents</h1>
    <ul>
        <li v-for="item in tocItems" :class="'toc-level' + item.level">
            <ref :to="item.id" />
        </li>
    </ul>
    <pagebreak />
</table-of-contents>

<markdown>
    # Offensive Security OSWP Exam Documentation {.in-toc.numbered}
    The Offensive Security OSWP exam documentation contains all efforts that were conducted in order to pass the Offensive Security Wireless Professional exam. This report will be graded from a standpoint of correctness and fullness to all aspects of the exam. The purpose of this report is to ensure that the student has the technical knowledge required to pass the qualifications for the Offensive Security Wireless Professional certification.

    ## Requirements {.in-toc.numbered}
    The student will be required to fill out this penetration testing report fully and to include the following sections:
    * Methodology walkthrough and detailed outline of steps taken
    * Each finding with included screenshots, walkthrough and sample commands
    * Any additional items that were not included
</markdown>
<pagebreak/>
    
<section>
    <h1 id="findings" class="in-toc numbered">Findings</h1>
    <div v-for="finding in findings">
        <markdown :text="finding.description" />
        <h2 :id="finding.id" class="in-toc numbered">{{ finding.title }}</h2>
        <div v-if="finding.proof">
            <h3 class="in-toc numbered">Proof</h3>
            <markdown :text="finding.proof" />
        </div>

        <div v-if="finding.screenshots">
            <h3 class="in-toc numbered">Screenshots</h3>
            <markdown :text="finding.screenshots" />
        </div>

         <div v-if="finding.steps">
            <h3 class="in-toc numbered">Steps</h3>
            <markdown :text="finding.steps" />
        </div>
        <pagebreak />
    </div>
</section>

<section v-if="report.appendix_sections.length > 0" class="appendix">
    <h1 id="appendix" class="in-toc numbered">Appendix</h1>

    <div v-for="appendix_section in report.appendix_sections">
        <h2 class="in-toc numbered">{{ appendix_section.title }}</h2>
        <markdown :text="appendix_section.content" />
    </div>
    <pagebreak />
</section>

<section>
    <div class="end-of-report">
        End of Report<br>
    </div>
    <div class="end-of-report">
        This report was rendered<br>
        by <a href="https://docs.sysreptor.com/">SysReptor</a> with<br>
        <span style="color:red;">&hearts;</span><br>
    </div>
</section>
"""
report_styles = """
@import "/assets/global/base.css";

/* Define variables */
:root {
    --color-risk-critical: #E83221;
    --color-risk-high: #FF9300;
    --color-risk-medium: #FFDA00;
    --color-risk-low: #4285F5;
    --color-risk-info: #00AE51;

    --color-cover-page-bg: #c37cc3; 
}

/* Font settings */
html {
    font-family: "Noto Sans", sans-serif;
    font-size: 10pt;
}


/* Global styles */
@page {
    size: A4 portrait;
    margin: 35mm 20mm 25mm 20mm;
}

a {
    font-style: italic;
    text-decoration: none;
    color: inherit;
}

pre code {
    border: 1px solid black;
    padding: 0.2em !important;
}
code {
    background-color: rgb(221, 221, 221);
}

th {
    background-color: #ABABAB;
    font-weight: bold;
}
tr.table-row-link td {
    padding: 0;
}
tr.table-row-link td a {
    display: block;
    padding: 0.3em;
    color: inherit;
    text-decoration: none;
    font-style: inherit;
}
.table-key {
    background-color: #ABABAB;
}


/* Classes for risk colors */
.risk-critical { color: var(--color-risk-critical) !important; font-weight: bold; }
.risk-high { color: var(--color-risk-high) !important; font-weight: bold; }
.risk-medium { color: var(--color-risk-medium) !important; font-weight: bold; }
.risk-low { color: var(--color-risk-low) !important; font-weight: bold; }
.risk-info { color: var(--color-risk-info) !important; font-weight: bold; }

.risk-bg-critical { background-color: var(--color-risk-critical) !important; color: white !important; }
.risk-bg-high { background-color: var(--color-risk-high) !important; }
.risk-bg-medium { background-color: var(--color-risk-medium) !important; }
.risk-bg-low { background-color: var(--color-risk-low) !important; }
.risk-bg-info { background-color: var(--color-risk-info) !important; }

/* Helper class for referencing page number */
.ref-page::before { 
    content: "" !important;
}
.ref-page::after {
  content: target-counter(attr(href), page) !important;
}
.ref-page .ref-title {
  display: none !important;
}

/* Table in finding chapters */
.finding-heading .table-key {
    height: 3em;
    width: 10em;
}


.end-of-report {
    text-align:center;
    font-style:italic;
    margin-top:70px;
    line-height:1.7;
}





/* #region footer */
@page {
    @bottom-left { content: element(footer-left); }
    @bottom-center { content: element(footer-center); }
    @bottom-right-corner { content: counter(page); }
}
#footer #footer-left { position: running(footer-left); }
#footer #footer-center { position: running(footer-center); }
/* #endregion footer */

/* #region watermark */
#watermark-osid {
    position: fixed;
    top: 9cm;
    left: 1cm;
    transform: rotate(-45deg);
    font-size: 90pt;
    text-transform: uppercase;
    opacity: 0.2;
}
/* #endregion watermark */

/* #region page-cover */
@page :first {
    /* Footer on the cover page */
    @bottom-right-corner {
        content: "";
    }
    @bottom-right {
        /* Page number */
        content: counter(page);
        font-size: 9pt;
        color: white
    }
    @bottom-left {
        content: "Confidential";
        text-transform: uppercase;
        font-style: italic;
        color: white;
    }
     /* Pentest title should not appear on cover page */
    @bottom-center {
        content: '';
    }
}
#page-cover-background{
    position: absolute;
    margin-top: -35mm;
    margin-left: -20mm;
    width: 210mm;
    height: 297mm;
    background-color: var(--color-cover-page-bg);
}
/* Title page elements */
#page-cover-title {
    position: absolute;
    top: 20mm;
    left: 0;
    width: 14cm;
    color: #ffffff;
}
#page-cover-title h1 {
    font-size: 32pt;
}
#page-cover-title h2 {
    font-size: 24pt;
}
#page-cover-student {
    position: absolute;
    top: 11cm;
    left: 0;
    width: 14cm;
    color: #ffffff;
}
#page-cover-osid {
    font-size: 14pt;
}
#page-cover-meta {
    line-height: 2em;
}
/* #endregion page-cover */

/* #region toc */
#toc li {
  list-style: none;
  margin: 0;
  padding: 0;
}
#toc .ref::before {
    padding-right: 0.5em;
}
#toc .ref::after {
    content: " " leader(".") " " target-counter(attr(href), page);
}
#toc .toc-level1 {
  font-size: 1.5rem;
  font-weight: bold;
  margin-top: 0.8rem;
}
#toc .toc-level2 {
  font-size: 1.2rem;
  font-weight: bold;
  margin-top: 0.5rem;
  margin-left: 2rem;
}
#toc .toc-level3 {
  font-size: 1rem;
  margin-top: 0.4rem;
  margin-left: 4rem;
}
#toc .toc-level4 {
  font-size: 1rem;
  margin-top: 0;
  margin-left: 6rem;
}
/* #endregion toc */
"""

[report_fields]
[report_fields.title]
type = "string"
label = "Title"
origin = "core"
default = "OSWP Exam Documentation"
required = true
spellcheck = true

[report_fields.mail]
type = "string"
label = "Mail"
origin = "custom"
default = "student@example.com"
required = true
spellcheck = false

[report_fields.osid]
type = "string"
label = "OSID"
origin = "custom"
default = "XXXXX"
required = true
spellcheck = false

[report_fields.lastname]
type = "string"
label = "Lastname"
origin = "custom"
default = "Doe"
required = true
spellcheck = false

[report_fields.firstname]
type = "string"
label = "Firstname"
origin = "custom"
default = "John"
required = true
spellcheck = false

[report_fields.watermark]
type = "boolean"
label = "Watermark"
origin = "custom"
default = false

[report_fields.report_date]
type = "date"
label = "Report Date"
origin = "custom"
required = true

[report_fields.report_version]
type = "string"
label = "Report Version"
origin = "custom"
default = "1.0"
required = true
spellcheck = false

[report_fields.appendix_sections]
type = "list"
label = "Additional Items Not Mentioned in the Report"
origin = "custom"
required = true

[report_fields.appendix_sections.items]
type = "object"
label = ""
origin = "custom"

[report_fields.appendix_sections.items.properties]
[report_fields.appendix_sections.items.properties.title]
type = "string"
label = "Title"
origin = "custom"
default = "TODO appendix title"
required = true
spellcheck = false

[report_fields.appendix_sections.items.properties.content]
type = "markdown"
label = "Content"
origin = "custom"
default = "TODO This section is placed for any additional items that were not mentioned in the overall report."
required = true

[[report_sections]]
id = "Student"
label = "Student"
fields = [
    "firstname",
    "lastname",
    "osid",
    "mail",
]

[[report_sections]]
id = "other"
label = "Document Control"
fields = [
    "title",
    "report_date",
    "report_version",
    "watermark",
]

[[report_sections]]
id = "appendix"
label = "Appendix"
fields = [
    "appendix_sections",
]

[finding_fields]
[finding_fields.title]
type = "string"
label = "Target"
origin = "core"
default = "TODO Target Name"
required = true
spellcheck = true

[finding_fields.cvss]
type = "cvss"
label = "CVSS (not required)"
origin = "core"
default = "n/a"
required = false

[finding_fields.description]
type = "markdown"
label = "Technical Description"
origin = "predefined"
default = "TODO A brief description of the attack chain with machine names, including the depth of compromise should be included here."
required = true

[finding_fields.proof]
type = "markdown"
label = "Proof"
origin = "custom"
default = "TODO Provide the contents of the \"Access Point X\" wireless network key."
required = true

[finding_fields.steps]
type = "markdown"
label = "Steps"
origin = "custom"
default = "TODO Provide a detailed account of your methodology in obtaining the \"Access Point X\" wireless network key. **The steps taken should be able to be easily followed and reproducible if necessary.**"
required = true

[finding_fields.screenshots]
type = "markdown"
label = "Screenshots"
origin = "custom"
default = "TODO Provide at least one screenshot of the successfully cracked \"Access Point X\" wireless network key and a screenshot of proof.txt."
required = true

[report_preview_data]
[report_preview_data.report]
title = "OSWP Exam Documentation"
mail = "student@example.com"
osid = "OS-XXXXX"
watermark = true
report_date = "2022-07-29"
report_version = "1.0"
firstname = "John"
lastname = "Doe"

[[report_preview_data.report.appendix_sections]]
title = "Appendix Title"
content = "Appendix content"

[[report_preview_data.findings]]
title = "Access Point X"
cvss = "n/a"
description = "TODO: A brief description of the attack chain with machine names, including the depth of compromise should be included here."
id = "30fa6ea9-64f0-4b95-a7ff-dcc2e1983d3f"
proof = "TODO Provide the contents of the \"Access Point X\" wireless network key."
steps = "TODO Provide a detailed account of your methodology in obtaining the \"Access Point X\" wireless network key. **The steps taken should be able to be easily followed and reproducible if necessary.**"
screenshots = "TODO Provide at least one screenshot of the successfully cracked \"Access Point X\" wireless network key and a screenshot of proof.txt."

[[assets]]
id = "1b6169aa-b720-4de0-b6ec-3dee7b52ec18"
name = "LICENSE"
