format = "templates/v2"
id = "b2d2ed06-b305-401f-88a6-369083d0ac46"
tags = [
    "web",
]
images = []

[[translations]]
id = "d20f4ab3-0588-4f69-8339-ef84101753d9"
is_main = true
language = "en-US"
status = "finished"

[translations.data]
title = "SQL Injection (SQLi)"
cvss = "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
summary = """
The web application processed user input in an insecure manner and was thus vulnerable to SQL injection. 
In an SQL injection attack, special input values in the web application are used to influence the application's SQL statements to its database. 
Depending on the database used and the design of the application, this may make it possible to read and modify the data stored in the database, perform administrative actions (e.g., shut down the DBMS), or in some cases even gain code execution and the accompanying complete control over the vulnerable server.
"""
description = """
We identified an SQL injection vulnerability in the web application and were able to access stored data in the database as a result.

**TODO: technical description**

SQL Injection is a common server-side vulnerability in web applications. 
It occurs when software developers create dynamic database queries that contain user input. 
In an attack, user input is crafted in such a way that the originally intended action of an SQL statement is changed. 
SQL injection vulnerabilities result from an application's failure to dynamically create database queries insecurely and to properly validate user input. 
They are based on the fact that the SQL language basically does not distinguish between control characters and data characters. 
In order to use a control character in the data part of an SQL statement, it must be encoded or escaped appropriately beforehand.

An SQL injection attack is therefore essentially carried out by inserting a control character such as `'` (single apostrophe) into the user input to place new commands that were not present in the original SQL statement. 
A simple example will demonstrate this process. 
The following SELECT statement contains a variable userId. 
The purpose of this statement is to get data of a user with a specific user id from the Users table.

```python
sqlStmnt = 'SELECT * FROM Users WHERE UserId = ' + userId;
```

An attacker could now use special user input to change the original intent of the SQL statement. 
For example, he could use the string `' or 1=1` as user input. 
In this case, the application would construct the following SQL statement:

```python
sqlStmnt = 'SELECT * FROM Users WHERE UserId = ' + ' or 1=1;
```

Instead of the data of a user with a specific user ID, the data of all users in the table is now returned to the attacker after executing the statement. 
This gives an attacker the ability to control the SQL statement in his own favor. 

There are a number of variants of SQL injection vulnerabilities, attacks and techniques that occur in different situations and depending on the database system used. 
However, what they all have in common is that, as in the example above, user input is always used to dynamically construct SQL statements. 
Successful SQL injection attacks can have far-reaching consequences. 
One would be the loss of confidentiality and integrity of the stored data. 
Attackers could gain read and possibly write access to sensitive data in the database. 
SQL injection could also compromise the authentication and authorization of the web application, allowing attackers to bypass existing access controls. 
In some cases, SQL injection can also be used to gain code execution, allowing an attacker to gain complete control over the vulnerable server.
"""
recommendation = """
* Use prepared statements throughout the application to effectively avoid SQL injection vulnerabilities. Prepared statements are parameterized statements and ensure that even if input values are manipulated, an attacker is unable to change the original intent of an SQL statement. 
* Use existing stored procedures by default where possible. Typically, stored procedures are implemented as secure parameterized queries and thus protect against SQL injections.
* Always validate all user input. Ensure that only input that is expected and valid for the application is accepted. You should not sanitize potentially malicious input.
* To reduce the potential damage of a successful SQL Injection attack, you should minimize the assigned privileges of the database user used according to the principle of least privilege.
* For detailed information and assistance on how to prevent SQL Injection vulnerabilities, see OWASP's linked SQL Injection Prevention Cheat Sheet.
"""
short_recommendation = """\
Make sure that Prepared Statements and Stored Procedures (where possible) are used throughout the application. \
This prevents the originally intended action of an SQL statement from being manipulated by an attacker.\
"""
references = [
    "https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet",
]
affected_components = [
    "TODO: affected component",
]

